#!/usr/bin/sh

. "$HOME/github/dwm-bar/Scripts/bandwidth"
. "$HOME/github/dwm-bar/Scripts/timeDBAR"
. "$HOME/github/dwm-bar/Scripts/dateDBAR"
. "$HOME/github/dwm-bar/Scripts/batteryDBAR"
. "$HOME/github/dwm-bar/Scripts/cpuDBAR"
. "$HOME/github/dwm-bar/Scripts/brightnessDBAR"
. "$HOME/github/dwm-bar/Scripts/memoryDBAR"
. "$HOME/github/dwm-bar/Scripts/musicDBAR"
. "$HOME/github/dwm-bar/Scripts/volumeDBAR"
. "$HOME/github/dwm-bar/Scripts/numlockDBAR"
# . "$HOME/github/dwm-bar/Scripts/torrentDBAR"
. "$HOME/github/dwm-bar/Scripts/musicDBAR"

while true;do
		xsetroot -name "$(musicDBAR)|$(bandwidth)|$(memoryDBAR)|$(brightnessDBAR)|$(volumeDBAR)|$(cpuDBAR)|$(batteryDBAR)|$(dateDBAR)|$(timeDBAR)|$(numlockDBAR)" 
		sleep 1  &
		echo $! > $HOME/github/dwm-bar/dwmpid
		wait $!  
	done

