#!/usr/bin/env sh

# trap finish 1 3 6 15

. "$HOME/github/dwm-bar/Scripts/timeDBAR"
. "$HOME/github/dwm-bar/Scripts/dateDBAR"
. "$HOME/github/dwm-bar/Scripts/batteryDBAR"
. "$HOME/github/dwm-bar/Scripts/cpuDBAR"
. "$HOME/github/dwm-bar/Scripts/brightnessDBAR"
. "$HOME/github/dwm-bar/Scripts/memoryDBAR"
. "$HOME/github/dwm-bar/Scripts/musicDBAR"
. "$HOME/github/dwm-bar/Scripts/volumeDBAR"


function dwmbar {
	while true
	do
		xsetroot -name "$(musicDBAR)|$(memoryDBAR)|$(brightnessDBAR)|$(volumeDBAR)|$(cpuDBAR)|$(batteryDBAR)|$(dateDBAR)|$(timeDBAR)"

		sleep 60 &
		echo $! > $HOME/github/dwm-bar/dwmpid
		wait $!

	done
}


# function finish {
# 	xsetroot -name "$(musicDBAR)|$(memoryDBAR)|$(brightnessDBAR)|$(cpuDBAR)|$(batteryDBAR)|$(dateDBAR)|$(timeDBAR)"
# }
dwmbar
