#!/usr/bin/env sh


batteryDBAR () {

	if ! [[ "$(acpi)" = "" ]];then 
		state=$(acpi | awk -F "[',:']" '{print $2}' | sed 's/\ //')
		declare -i perc=$(acpi | awk -F "[',']" '{print $2}' | sed 's/\%//; s/\ //')
		time="("$(acpi | awk -F "[':,']" '{print $4":"$5}' | sed 's/\ //')")"

		if [[ "$state" == 'Discharging' ]];then
			if [[ $perc -le 5 ]];then
				bCase=1
				notify-send -u critical "$perc% Low battery\n$time"
			elif [[ $perc -le 15 ]];then
				color="#FF0000"
				bat='  '
				notify-send -u critical "$bat$perc% Low battery\n$time"
			elif [[ $perc -le 30 ]];then
				color="#FFAE00"
				bat='  '
			elif [[ $perc -le 50 ]];then
				color="#FFF600"
				bat='  '
			elif [[ $perc -le 75 ]];then
				color="#A8FF00"
				bat='  '
			elif [[ $perc -le 100 ]];then
				color="#A8FF00"
				bat='  '
			fi
		elif [[ "$state" == 'Charging' ]];then
			color="#FFFFFF"
			bat='  '
		elif [[ "$state" == "Unknown" ]];then
			color="#FFFFFF"
			bat='  '
		elif [[ "$state" == "Full" ]];then
			bCase=2
			notify-send -u critical "Battery Full"

		fi

		if [[ $bCase == 1 ]];then 
			printf " ^c#FF0000^Low battery^d^ "
		elif [[ $bCase == 2 ]];then
			printf " ^c#FF0000^Battery full^d^ "
		else 
			printf " ^c$color^$perc%%$bat$time^d^ "
		fi
	else
		printf " ^c#FF0000^^d^ "
	fi
}

batteryDBAR
