#!/usr/bin/env sh

memoryDBAR () {
	used=$(free -h | awk '/^Mem:/ {print $3}' | sed 's/Gi//;s/Mi//')
	total=$(free -h | awk '/^Mem:/ {print $2}' | sed 's/Gi//')
	unit=$(free -h | awk '/^Mem:/ {print $3}' | tr -d [:digit:][:punct])

	if [[ "$unit" == "Mi" ]];then
		used=$(echo "scale=3;$used/1000" | bc)
	fi

	perc=$(echo "scale=1;$used*100/$total" | bc)

	if [[ $perc -ge 85 ]];then
		color="#FF0000"
	elif [[ $perc -ge 70 ]];then
		color="#FFAE00"
	elif [[ $perc -ge 50 ]];then
		color="#FFF600"
	elif [[ $perc -ge 30 ]];then
		color="#A8FF00"
	elif [[ $perc -ge 15 ]];then
		color="#A8FF00"
	else
		color="#FFFFFF"
	fi

	printf " ^c$color^ $perc%%^d^ "
}

memoryDBAR
