#!/bin/env sh

memoryDBAR () {
	used=$(free -h | awk '/^Mem:/ {print $3}' | sed 's/Gi//;s/Mi//')
	total=$(free -h | awk '/^Mem:/ {print $2}' | sed 's/Gi//')
	unit=$(free -h | awk '/^Mem:/ {print $3}' | tr -d [:digit:][:punct])

	if [[ "$unit" == "Mi" ]];then
		used=$(echo "scale=3;$used/1000" | bc)
	fi

	perc=$(echo "scale=1;$used*100/$total" | bc)

	printf "  $perc%% "
}

memoryDBAR
