#!/usr/bin/env sh

musicDBAR () {
	if ! [[ "$(playerctl status 2>&1)" = "No players found" ]];then
		playIcon="^c#12de41^^d^";
		pauseIcon="^c#DA5F05^^d^";
		stopIcon="^c#DA5F05^^d^";

		playerStatus=$(playerctl status);
		songArtist="$(playerctl metadata artist)";

		fname=$(cmus-remote -Q | awk -v FS='/' '/^file/ {print $NF}' | sed "s/.mp3//;s/\&/and/;s/\[HD\]//");

		songArtist="${songArtist:-$fname}";
		songTitle=$(playerctl metadata title);
		songInfo="$songArtist - $songTitle";
		songDuration="";
		elapsedTime=$(playerctl metadata --format "{{ duration(position) }}");
		songLength=$(playerctl metadata --format "{{ duration(mpris:length) }}");
		songDuration=" [$elapsedTime/$songLength]";

		if [[ "${playerStatus^}" = "Paused" ]]; then
			echo " $songInfo$songDuration $pauseIcon ";
		elif [[ "${playerStatus^}" = "Playing" ]]; then
			echo " $songInfo$songDuration ";
		elif [[ "${playerStatus^}" = "Stopped" ]]; then
			echo " Stopped $stopIcon ";
		fi
	fi
}

musicDBAR
