#!/usr/bin/env sh

numlockDBAR () {

	state=$(xset -q | grep -F "Num Lock" | awk '{print $8}')

	if [[ "$state" == "on" ]];then
		color="#00FF00"
	elif [[ "$state" == "off" ]];then
		color="#222222"
	fi

	printf " ^c$color^^d^ "

}

numlockDBAR
