#!/usr/bin/env sh

torrentDBAR () {

	if ! [[ "$(ps -axch | grep transmission-da)" = "" ]];then
		color="#00FF00"
	else
		color="#FF0000"
	fi

	transmission-remote -l | grep % |
		sed " # This first sed command is to ensure a desirable order with sort
			s/.*Stopped.*/A/g;
			s/.*Seeding.*/Z/g;
			s/.*100%.*/N/g;
			s/.*Idle.*/B/g;
			s/.*Uploading.*/L/g;
			s/.*%.*/M/g" |
				sort -h | uniq -c | sed " # Now we replace the standin letters with icons.
							s/A/^c#FF0000^⏹^d^/g;
							s/B/^c#ffa500^⧗^d^/g;
							s/L/^c#1DDAD7^^d^/g;
							s/M/^c#1DDAD7^^d^/g;
							s/N/^c#00FF00^✔^d^/g;
							s/Z/^c#00FF00^🙐^d^/g" | awk '{print $2, $1}' | sed -e "s/ $//g" | tr '\n' ' '
							if [[ "$(transmission-remote -l | grep Sum | awk '{print $2}')" -eq "None" ]];then
								printf "^c$color^⓿ ^d^"
							fi
						}

torrentDBAR
