#!/usr/bin/env sh

torrentDBAR () {
transmission-remote -l | grep % |
	sed " # This first sed command is to ensure a desirable order with sort
	s/.*Stopped.*/A/g;
	s/.*Seeding.*/Z/g;
	s/.*100%.*/N/g;
	s/.*Idle.*/B/g;
	s/.*Uploading.*/L/g;
	s/.*%.*/M/g" |
		sort -h | uniq -c | sed " # Now we replace the standin letters with icons.
				s/A/^c#FF0000^⏹^d^/g;
				s/B/^c#ffa500^⧗^d^/g;
				s/L/^c#ffa500^^d^/g;
				s/M/^c#ffa500^^d^/g;
				s/N/^c#00FF00^✔^d^/g;
				s/Z/^c#00FF00^🙐^d^/g" | awk '{print $2, $1}' | sed -e "s/ $//g" | tr '\n' ' '
			}

torrentDBAR
