#!/usr/bin/env sh

volumeDBAR () {
	sp0=
	sp1=
	sp2=
	spmute=
	

	toggle=$(amixer | awk '/^  Front Left: Playback/ {print $6}' | sed 's/\[//;s/\]//')

	case $BLOCK_BUTTON in
		1) pactl set-sink-mute 0 toggle ;;
		3) i3-msg -q exec pavucontrol;;
		4) pactl set-sink-volume 0 +5%
			if [[ "$toggle" == "off" ]]
			then
				pactl set-sink-mute 0 toggle
			fi;;
		5) pactl set-sink-volume 0 -5%
			if [[ "$toggle" == "off" ]]
			then
				pactl set-sink-mute 0 toggle
			fi;;
	esac

	declare -i vol=$(amixer | awk '/^  Front Left: Playback/ {print $5}' | sed 's/\[//;s/\]//;s/\%//')

	toggle=$(amixer | awk '/^  Front Left: Playback/ {print $6}' | sed 's/\[//;s/\]//')

	if [[ "$toggle" == "on" ]];then
		if [[ $vol -le 50 ]]
		then
			if [[ $vol -le 5 ]]
			then
				icon=$sp0
			else
				icon=$sp1
			fi
		else
			icon=$sp2
		fi
	else
		icon=$spmute
	fi

	printf " $icon $vol%% "
}

volumeDBAR
