#!/usr/bin/env sh

volumeDBAR () {
	sp0=
	sp1=
	sp2=
	spmute=
	
	toggle=$(amixer | awk '/^  Front Left: Playback/ {print $6}' | sed 's/\[//;s/\]//')
	declare -i vol=$(amixer | awk '/^  Front Left: Playback/ {print $5}' | sed 's/\[//;s/\]//;s/\%//')

	if [[ "$toggle" == "on" ]];then
		if [[ $vol -le 50 ]]
		then
			if [[ $vol -le 5 ]]
			then
				icon=$sp0
			else
				icon=$sp1
			fi
		else
			icon=$sp2
		fi
	else
		icon=$spmute
	fi

	printf " $icon $vol%% "
}

volumeDBAR
